### PR TITLE
feat(api keys): add loading state for revoking all api keys

### PR DESCRIPTION
**Pull request by Camc314**

### CODE REVIEW

**Comment by ThibaultNocchi** [comment]
Couldn't we use the global Nuxt loading state for this?

**Comment by Camc314** [comment]
What do you mean? The loading bar at the top of the screen?

A similar implementation to this is on the login screen, then the sign in button is pressed

**Comment by ThibaultNocchi** [comment]
I was talking about, if it's possible, just binding to axios loading state in order to not have to track ourselves the syncing state?

**Comment by Camc314** [comment]
I'm not aware of any way to do that.

**Review by ThibaultNocchi — APPROVED** [review]
Yeah, maybe eventually we could look into how this is usually solved. But this is still a pretty good and error-proof way :p

**Pull request merged**
