### PR TITLE
feat(seasons): Add links back to a series and season from an episode.

### LINKED ISSUE #1822: No link back to a series or season from an episode.
### Description of the bug

No link back to a series or season from an episode.

### Steps to reproduce

Go to any episode, no link back to a series or season from an episode.

### Expected behavior

Should have a link back to a series or season from an episode.

### Logs

_No response_

### Screenshots

_No response_

### Platform

Linux

### Browser

Chrome

### Jellyfin server version

10.8.8

### Additional context

```text
I'm creating a merge request for this
```

### PR DESCRIPTION
**Pull request by BrianCArnold**
This fixes #1822.

It also parallelizes getting seasons from the server, instead of having to wait for each list of episodes in a season to load before starting to load the next season's list of episodes.

### CODE REVIEW

**Comment by ThibaultNocchi** [comment]
Hey @BrianCArnold, sorry for taking this long to answer.

We're currently migrating to Vue 3 in the `vite` branch, could you apply your fix in there please?

Thanks!

**Comment by ferferga** [comment]
@BrianCArnold Hey, ``vite`` has been merged now and the client is fully on Vue 3. I'm removing the blocked label.
Can you please rebase this so we can apply it?

**Comment by BrianCArnold** [comment]
Absolutely, I'll work on that in the next couple days (if I managed to remember, ADHD is a pain)

**Comment by BrianCArnold** [comment]
Hey, guess who just remembered this exists? Gonna work on it now.

**Comment by BrianCArnold** [comment]
Superseded by !2135

**Pull request closed without merging**
