### PR TITLE
Add support for Live TV

### PR DESCRIPTION
**Pull request by AhsanFazal**
# Why?

I noticed that my Live TV channels were not working with JellyVue. This PR is serves the purpose of allowing basic functionality for Live TV: list TV Channels in library view and successfully stream them to the client.

The bulk of the Live TV functionality is still missing, like an EPG view, alternative sorting of channels, viewing channels in groups, etc.

I do intend to add these features in an upcoming PR.

# What?

## Live TV Library view
image

## Live TV Item view
image

## Playing Live TV streams
image

# How?

1. Load all Live TV Channels. See **[frontend/src/pages/library/_itemId/index.vue](https://github.com/jellyfin/jellyfin-vue/compare/master...AhsanFazal:jellyfin-vue:feature/live-tv#diff-d3a19152d6beb708e111838c007c1f0034b07d500edb37de304be87c526e9549)**

2. Style their card views and item views. See **[frontend/src/components/Layout/Images/Blurhash/BlurhashImage.vue](https://github.com/jellyfin/jellyfin-vue/compare/master...AhsanFazal:jellyfin-vue:feature/live-tv#diff-ad10b5b9c628de2e7d36b01914cabb319a76a5d605d55bd070acb7d4309d0ea3)** and **[frontend/src/pages/item/_itemId/index.vue](https://github.com/jellyfin/jellyfin-vue/compare/master...AhsanFazal:jellyfin-vue:feature/live-tv#diff-edc458825e27b03ac8297d5b96ffe74618ac4f9754a4c9ac473f63d251f8cef9)**

3. Play them. See **[frontend/src/store/playbackManager.ts](https://github.com/jellyfin/jellyfin-vue/compare/master...AhsanFazal:jellyfin-vue:feature/live-tv#diff-585c9cf8ceacb4413396aff087dea6343ab0bf9d4debf50fa4b9ae8a684406c0)**

### CODE REVIEW

**Review by ferferga — CHANGES_REQUESTED** [review]
Hello, thank you very much! A few things before diving deep into the code.

1. Please follow the commit name conventions: https://github.com/jellyfin/jellyfin-vue/wiki/Contributing#conventions
2. Probably you tried to mimick Web's design, but don't you think there's a better way to display the channel logos than using a card? Don't we have other apps we can inspire others? The design of the web client is horrible for logos and we shouldn't mimick that imo.

**Comment by AhsanFazal** [comment]
1. Oops! I'll rename the commits.
2. You're 100% right and that was also the first thought I had. I'm kinda new to contributing to open source projects, so I didn't want to "overstep". But I'll get on that in my next few commits!

**Comment by ferferga** [comment]
@AhsanFazal

1. Also we use rebase instead of merge commits, so get these out as well. Ping me if you need any help.
2. Same as above, find how Live TV is commonly implemented in other places UI/UX-wise, attach some screenshots/descriptions here so we can give you additional feedback as well. If you get stuck at some point, we can chime in and commit directly to your branch (if you don't mind) too!

**Comment by ferferga** [comment]
@AhsanFazal Any update about this?

**Comment by ferferga** [comment]
Closing due to the lack of feedback

**Pull request closed without merging**
