### PR TITLE
fix(series-item): removed original title if it is the same as the name

### PR DESCRIPTION
**Pull request by MarcelCoding**
#890 -> was only for a film
This not also fixes this Issue on a series.

see https://github.com/jellyfin/jellyfin-vue/issues/836#issuecomment-804008091

### CODE REVIEW

**Comment by ferferga** [comment]
Maybe we can move this to the layout we share across all the pages instead of doing this in a per page basis?

@MrTimscampi @ThibaultNocchi @Camc314 @dkanada thoughts?

**Comment by MrTimscampi** [comment]
> Maybe we can move this to the layout we share across all the pages instead of doing this in a per page basis?

Not really, because the layout is only for the columns. This check is per item type, since a bunch of them don't even have original titles.

The way the title is setup varies per item type, so imo that should stay in each template, to avoid falling into a jf-web situation where we have 25 lines to generate the title block and barely anyone understands what goes on in there.

**Comment by ferferga** [comment]
Fair enough 👍🏻

**Review by ferferga — APPROVED** [review]

**Review by MrTimscampi — APPROVED** [review]

**Review by ThibaultNocchi — APPROVED** [review]

**Comment by ferferga** [comment]
@jellyfin-bot rebase

**Pull request merged**
