### PR TITLE
Disable nuxt telemetry

### PR DESCRIPTION
**Pull request by ferferga**

### CODE REVIEW

**Review by MrTimscampi — COMMENTED** [review]
Seems like you need to run Prettier on the config file (PS: If you use VSCode, install the Prettier extension and this should happen automatically on save, with the config we ship with the project).

**Comment by ferferga** [comment]
@MrTimscampi Lint errors seems to be caused by other files. I already ran prettier and comment's tabulation are in line with the other ones 🤔.

**Review by MrTimscampi — APPROVED** [review]

**Comment by MrTimscampi** [comment]
@ferferga Seems like the comment block had one too many spaces:
image

I fixed it myself, since I had the branch checked out to run the linter on it.

**Comment by ferferga** [comment]
@MrTimscampi Oops!

Thank you very much! <3

**Pull request merged**
