### PR TITLE
Allow for restricted HTML tag usage in the Login Disclaimer

### PR DESCRIPTION
**Pull request by realashleybailey**
Allow for restricted HTML tag usage in the Login Disclaimer, tag usage is restricted to the use of the following tags.
b, i, h1, h2, h3, h4, h5, h6, a, p

Fix Progress Bar underlapping the navigation bar on mobile devices and small screens.

### CODE REVIEW

**Comment by ThibaultNocchi** [comment]
Hello, thanks for the PR.

We're currently in the process of migrating the codebase to Vue 3 in the `vite` branch, you may want to add your feature there and check if the fix is still needed.

Also I'd ask @ferferga for what we thought about HTML in user filled values, I don't have a strong opinion about either way but iirc we did it this way cause we didn't want it. He'll decide.

**Comment by realashleybailey** [comment]
> 

No worries I will pull the vite branch and see about the modifications over there, I understand not wanting HTML in user-filled areas I only suggest it because I know that jellyfin-web allows for it and I know in my case I defiantly use it for the disclaimer page to be able to add further information in a stylised way and to be able to add URL links in the disclaimer, if its not something you wish for jellyfin-vue that's no worries, I think HTML could be good along as DOM purify restricts its to very few HTML tags but I will leave it up to your guys decision :)

**Comment by ferferga** [comment]
@realashleybailey I think at some point we wanted to move to markdown, to ensure no XSS and a consistent experience across all devices.

But I guess this is something that should be discussed at jellyfin-meta. I'm open to do that rightaway instead of the current sanitisation, which is only a patch over a patch in reality.

**Comment by realashleybailey** [comment]
That sounds good to me, I will continue to focus my efforts on fixing some of the UI problems I noticed on `jellyfin-vue:vite` and will wait further for any word on whether we are implementing markdown. Thank you @ferferga hope you have great day.

**Pull request closed without merging**
