### PR TITLE
refactor: remove hls.js

### LINKED ISSUE #1518: fMP4 with AAC playback doesn't work with Shaka 3.2.0
### Description of the bug

Playing fMP4 files with AAC with Shaka 3.2.0 doesn't work. TS and AAC works, and 3.1.2 works.

Current solution is to disable AAC with fMP4 for now.

### Steps to reproduce

Play a file transcoded to a fMP4 container with AAC audio in it.

### Expected behavior

It shoudl work

### Logs

_No response_

### Screenshots

_No response_

### Platform

Linux

### Browser

Firefox

### Jellyfin server version

10.7.7

### Additional context

Waiting for feedbacks from here: https://github.com/google/shaka-player/issues/3691

Maybe it also relates to #1484?

### PR DESCRIPTION
**Pull request by ferferga**
Fixes #1518

Related ticket: https://github.com/shaka-project/shaka-player/pull/4241

### CODE REVIEW

**Review by ThibaultNocchi — CHANGES_REQUESTED** [review]
All good for me, except the stretch button that doesn't work. Either we remove it or we fix it? :)

**Comment by ferferga** [comment]
@ThibaultNocchi Tested in master (as of [c526428](https://github.com/jellyfin/jellyfin-vue/commit/c5264283a8b9a813f0737968fb6739983d2229cc)) and the stretch button is not functional for me (only a scrollbar appears below the video, but nothing else), so this is not a regression

**Review by ThibaultNocchi — APPROVED** [review]

**Comment by ThibaultNocchi** [comment]
Stretch has been fixed in the latest commit

**Comment by ferferga** [comment]
@jellyfin-bot rebase

**Pull request merged**
