### PR TITLE
test(playback store): add tests for playback store

### PR DESCRIPTION
**Pull request by Camc314**
Adds tests for playback manager store

Also fixes adding duplicate items to the queue

### CODE REVIEW

**Comment by ferferga** [comment]
What's wrong with duplicates in queue? I might shuffle my whole collection and then add that same item to play next.

**Comment by Camc314** [comment]
Say you had a queue of a, b, c, d. And you added a to the queue again. If the current item index was over 1, a wouldn't get added to the queue

**Comment by ferferga** [comment]
Just a little example to see if I understood it right:

So, in case I have a, b, c, d and I want to re-add a:

* Won't work if I use Play Next: so a, a, b, c, d

* Will work if I queue it: so a, b, c, d, a it's possible.

**Comment by Camc314** [comment]
Almost, neither will work. Previously we were using `Union`, that means that you can never have a duplicate item in the queue.

**Review by ferferga — APPROVED** [review]

**Pull request merged**
