### PR TITLE
fix(card): temporary fallback fix for thumbs

### PR DESCRIPTION
**Pull request by MrTimscampi**

### CODE REVIEW

**Review by Camc314 — APPROVED** [review]

**Review by ferferga — COMMENTED** [review]
I won't block this of course, but in my opinion, it's a waste of effort to merge this fix, then my PR and then another PR that removes this fix.

This issue is also present in my PR, (I added some media to check, don't have all the types of images in my library), so I'd rather merge #520 first and then rebase this to add the fixes or cherry-pick them there. 

For some time without those images I don't think nothing will be wrong :P.

**Comment by MrTimscampi** [comment]
> For some time without those images I don't think nothing will be wrong :P.

I agree, it was merely as a courtesy for people using the client, but I don't know of anyone using the client daily yet, so it might not be needed for now.

**Comment by ferferga** [comment]
Blocked until #520

**Comment by ferferga** [comment]
@MrTimscampi Does this need rebasing now that #520 is in?

**Comment by MrTimscampi** [comment]
Closing this in favor of a future proper refactoring of the imageHelper.

**Pull request closed without merging**
