### PR TITLE
fix(default.vue): dark mode toggle localization

### PR DESCRIPTION
**Pull request by ThibaultNocchi**
Also, I think weblate is adding space for indentation while our lint rules remove them. Do you think it'd be possible to fix this?

### CODE REVIEW

**Comment by Camc314** [comment]
Locales shouldn't be edited directly, it should be modified on Weblate to avoid issues

**Comment by ThibaultNocchi** [comment]
So to add a new one I should only add it manually to en.json?

**Comment by MrTimscampi** [comment]
> So to add a new one I should only add it manually to en.json?

Ideally, yes :)

**Comment by ThibaultNocchi** [comment]
Done!

**Review by Camc314 — APPROVED** [review]

**Review by MrTimscampi — APPROVED** [review]

**Pull request merged**
