### PR TITLE
fix(router): 404 on reloads

### LINKED ISSUE #1683: [Docker - nginx] 404 when refreshing detail pages (/*/*)
### Description of the bug

I ran the latest unstable image on docker, on 80:80 but I have a problem.

Every time I refresh the page, this from 404, except for the paths / and / * /

Excluding Login and Host page, everything that is /*/* returns 404 (summing up, the detail pages).

Making a list:

It works
- Home
- Login / Host
- Settings
- Metadata

It does not work
- library/*
- item/*
- series/*

I don't have some types of elements and I don't know if there are other specific paths, however I think it is also reflected in any other detail pages.

### Steps to reproduce

docker pull jellyfin/jellyfin-vue:unstable
docker run -p 80:80 jellyfin/jellyfin-vue:unstable
Go to localhost (or wathever), login
Go to some library or item or series page
Refresh (F5) 

image

### Expected behavior

The page reloads correctly

### Screenshots

image

### Platform

Windows

### Browser

Chrome

### Jellyfin server version

10.7.7

### PR DESCRIPTION
**Pull request by ferferga**
Turns out this was easier than I expected. Should fix #1683 

I tested a few routes and all of them worked but items, so I fixed their path resolution. I don't know if somewhere else changes are needed. @doc-code-hub Care to pull this branch and test extensively if all your tests pass now?

### CODE REVIEW

**Comment by doc-code-hub** [comment]
Ah, the links were really different!

But you know what? The thing is, I don't find this style of url very nice... Don't you?

That's why i've dove some search and made this PR #1685

**Comment by doc-code-hub** [comment]
`Care to pull this branch and test extensively if all your tests pass now?`

Tomorrow i can take a look, yes!

**Comment by ferferga** [comment]
> Ah, the links were really different!
> 
> But you know what? The thing is, I don't find this style of url very nice... Don't you?
> 
> That's why i've dove some search and made this PR #1685

See my reply to the linked PR please :)

**Comment by doc-code-hub** [comment]
I've seen and I understand... I'll keep the commit for myself :)

I'll be back tomorrow to try your PR :)

**Review by ThibaultNocchi — APPROVED** [review]

**Comment by ThibaultNocchi** [comment]
This also changes the default routing mode to "hash".

**Pull request merged**
