### PR TITLE
feat: add missing context menu items

### LINKED ISSUE #1950: Song item detected as MusicAlbum instead of Audio in Context Menu
### Description of the bug

If you try to open the item context menu on the Music Album page for the song, it got detected or marked as `MusicAlbum` instead of `Audio`.

### Steps to reproduce

1. Open a Music Album
2. Click on the context menu for a song (not the album itself)

### Expected behavior

The song is marked as `Audio`.

### Logs

_No response_

### Screenshots

https://user-images.githubusercontent.com/34302902/231725309-908a837a-ef54-417d-9c65-47777d5507cc.mp4

Example of a song in an album marked as `MusicAlbum` instead of `Audio`

Jellyfin

Jellyfin-web version that are correct.

### Platform

Windows

### Browser

Firefox

### Jellyfin server version

10.8.9

### Additional context

Using a modified JF-Vue that are based on https://github.com/jellyfin/jellyfin-vue/commit/16955dd87083d8059b060f57608e084ab2ccf5d0

### PR DESCRIPTION
**Pull request by noaione**
Implemented almost every context menu item that are missing from JF-Vue

Added the following item:
- [x] Refresh metadata (on anything other than Library)
- [x] Media Info
- [x] Copy Stream URL
- [x] Download single/all
- [x] Delete media
- [x] Instant mix
- [x] Identify

And maybe implement this:
- [ ] Add to playlist (maybe wait #1820)

Also Fix #1950 

I didn't know that much Vue so any feedback is appreciated.

### CODE REVIEW

**Comment by noaione** [comment]
I forgot multiple streams is a thing, should be supported now.

**Comment by ferferga** [comment]
@noaione I've been writing some review comments (but they're still pending, because I wanted to publish them once I reviewed all the code).

However, this PR is getting bigger and bigger... Would you mind splitting it in multiple PRs, so reviews get much easier, both for you and us?

**Comment by noaione** [comment]
Is it fine if some bundled together? Since they shared some code and I don't really know how to split it.

**Comment by noaione** [comment]
Closing since the PR has been split into a "smaller" one

PR 1: #1962 (Copy/Download/Media Info)
PR 2: #1963 (Refresh metadata)
PR 3: #1964 (Delete item)
PR 4: #1965 (Instant mix)
PR 5: #1966 (Identify)
PR 6: Blocked by other PR 1-5 (Add multiple streams support)

**Pull request closed without merging**
