### PR TITLE
chore: add newly opened Pull Requests to 'Ongoing development' project

### PR DESCRIPTION
**Pull request by ferferga**
Created an action that adds all the new Pull Requests to the "Ongoing development" project, so reviewed PRs can be tracked easily.

### CODE REVIEW

**Comment by ferferga** [comment]
@jellyfin/core According to this, we *shouldn't* need a token, but the action is failing.

**Review by ThibaultNocchi — APPROVED** [review]
Couldn't we also sort approved PR to a column?

**Comment by ferferga** [comment]
@ThibaultNocchi That's done automatically by GitHub. The only automation step in the chain that we were lacking was the "add to the project" part :).

**Comment by anthonylavado** [comment]
@ferferga So it's not working right now? I can set up a token with the bot if needed.

**Comment by ferferga** [comment]
@anthonylavado Yes please, so I can discard that.

**Review by MrTimscampi — APPROVED** [review]
As soon as we have the go from Core, we can merge this ;)

**Review by ThibaultNocchi — APPROVED** [review]

**Comment by MrTimscampi** [comment]
Merging this, since the token works in jf-web, so it should work here too when merged.

**Comment by ferferga** [comment]
@MrTimscampi It's not the same token :(

This action requires special permissions, the one for labeler is not enough. I tested it in my repo and the token is mandatory in org repos.

**Pull request merged**
