### PR TITLE
chore: upgrade to Vue 3

### PR DESCRIPTION
**Pull request by ferferga**
**THIS PR WILL BE MERGED ON MONDAY 3rd**

**TENTATIVE CHECKLIST**

*Might change depending on current situation, but I'll try to keep this up to date*

*I don't see all these tasks as mandatory for the merge, but I feel the most of them we had, better experience*

- [x] #1889
- [x] #1884
- [x] #1878 
- [x] https://github.com/vuetifyjs/vuetify/issues/16604
- [x] Create an entrypoint script for Docker, so environment variables are written to the new ``config.json`` file upon every container spin up: https://github.com/jellyfin/jellyfin-vue/blob/vite/frontend/public/config.json #1901
- [x] https://github.com/npm/cli/issues/6099 or https://github.com/actions/setup-node/issues/712 (related to #1886)
- [x] Get the maximum amount of components/pages refactored into Composition API and a lot of logic flaws (specially regarding Metadata editor) fixed #1892 
- [ ] Clean up the maximum amount of unused CSS classes and style hacks (Vuetify 2 needed a lot of those, but they no longer are necessary in a lot of places, so we should revisit every component to check that).
- [ ] Migrate to `MediaCapabilities` API for video and audio profile generation. This will remove a lot of legacy code and improve compatibility, since our profile generation is spaghetti. 
- [x] Get DraggableQueue working again (investigate VueUse's draggables or neodrag.dev, which seems a modern alternative to Sortable.JS, with better maintenance than the Sortable.JS Vue 3 version). #1909 
- [x] Fix the biggest amount of type and lint errors
- [x] Fix fullscreen music player style: #1899 
- [ ] Item store reactivity
- [x] Draft and tag a 0.2.0 release for master branch
- [ ] Merge this and all the renovate PRs in the following order. Tag 0.3.0 release afterwards:
       * #1738 
       * #1740 
       * #1770
       * #1765
       * #1838

### CODE REVIEW

**Comment by gibahjoe** [comment]
Hi, Is there a checklist of features that have been migrated from the master branch? Also is there one for features that have been migrated for jellyfin web?

I guess I just want to know how you are keeping track of your progress.

**Comment by ThibaultNocchi** [comment]
@gibahjoe Sorry for taking a couple of days to answer.

To quickly answer, we mainly handle this between @ferferga and I. But we're present on Matrix on the Vue channel: https://matrix.to/#/%23jellyfin-vue%3Amatrix.org

For the `vite` branch, we think there's only the video player branch left (I need to polish it up but it's all around working), the cleanup branch from @aweebs, search fix of @Janbong and linters fix. 

For an all around feature parity with web, the major point is the settings page and all admin feature. I'll let @ferferga explain more in details. 

Feel free to chime in on matrix if you want more direct chat :)

**Comment by ferferga** [comment]
@gibahjoe Added a quick checklist with what I think it's still pending for a somewhat stable merge (bugs will still pop here and there for a while, of course, but the intention is to get this branch merged as soon as possible to not get master branch frozen for longer)

@ThibaultNocchi Feel free to add somethinmg if I missed it or even elaborate a more concise description, I don't mind edits to my comments :)

**Comment by aweebs** [comment]
There's also several components that are waiting on vuetify 3 component implementations, search `TODO: Wait for Vuetify 3.1`. Is the plan to merge before those are implemented?

**Comment by ferferga** [comment]
@aweebs The idea is to merge in the best state possible to unfreeze master, but we expect bugs and changed features from master. The idea is to progressively polish them as soon as we notice them or we get issues.

As such, Tiw and me discussed about this internally and we want to merge without waiting for Vuetify components. When we're on master, we will start to receive automatic renovate PRs for the dependencies, which we don't get a the moment and we don't want to apply unless strictly necessary for getting bug fixes (or the fixes for the types in VGrid and VRow, as mentioned in this PR's description) to not mess too much with package-lock.json conflicts and have a better commit history. With those automatic updates, progressively reimplementing them it's going to be much easier and don't require our constant attention to Vuetify (since we get automatic changelogs from renovate).

The missing components are not that important for already having a good experience with the client, so TLDR **no, we're not going to wait for the missing Vuetify components**.

**Pull request merged**
