### PR TITLE
Add more library sort options

### LINKED ISSUE #1959: More sorting options for libraries
### Description of the bug

Maybe I'm blind and can't find an obvious "feature parity" issue for the jellyfin-vue project, please close this if so. 

I'm missing sorting options for libraries, specifically the one in jellyfin-web called "Date Added" which sorts media after when it was added to the library. Currently it's pretty difficult to find newly added stuff using the vue client, which is how I find media most of the time.

### Steps to reproduce

Only available options currently are Name, Rating and Release date

### Expected behavior

Should have the same sorting options as jellyfin-web

### Logs

_No response_

### Screenshots

_No response_

### Platform

Linux

### Browser

Firefox

### Jellyfin server version

10.8.9

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by The-Noah**
I added two more (missing) sort options to the library page, specifically `DateCreated` and `CommunityRating`.

Closes #1959

### CODE REVIEW

**Review by ferferga — APPROVED** [review]

**Comment by ferferga** [comment]
Is there any chance we can get the others added too? So we're truly in feature parity to web in that regard

**Comment by The-Noah** [comment]
Yeah, I can add the others.

`Runtime`, `date played` and `critics rating`

I could also do `parental rating`, but to me it doesn't make any sense to sort by that field, I only think of filtering by that. Same with `play count`. I can add those as well if wanted though.

**Comment by ferferga** [comment]
@The-Noah Add them just in case, shouldn't harm and we get feature-parity in that regard :)

**Comment by ferferga** [comment]
@The-Noah Any update on this? :)

**Comment by The-Noah** [comment]
@ferferga sorry I got held up with work and didn't have time to finish before going out of town. I'll try to have it completed by end of next week.

**Comment by ferferga** [comment]
@The-Noah No worries, no rush at all! I'm super busy lately too, just checking if you were still interested! 😊

**Pull request merged**
