### PR TITLE
fix(playback): fixes uncentered album art on playback page. Fixes #558

### LINKED ISSUE #558: Album covers are not always centered in the full screen music UI
Perhaps this is an upstream issue.

### PR DESCRIPTION
**Pull request by Camc314**
**Before**

image

**After**

image

### CODE REVIEW

**Comment by ferferga** [comment]
This makes matter worse for single covers:

image

Multiple covers are also worse centered than before when they're not in the first slide (now they are moved to the left side instead of the right):

image

**Before for reference**

image


image

**Review by ferferga — CHANGES_REQUESTED** [review]
Specified above

**Comment by Camc314** [comment]
Hmm I can't seem to reproduce what you're seeing. For me, after the changes, irrespective of the number of items currently playing, it seems to be centered.

**Comment by ferferga** [comment]
@Camc314 Which browser are you using?

My screen is a standard 1920x1080 24", nothing fancy in that side.

**Comment by Camc314** [comment]
Similar, 27in 1080p

**Comment by Camc314** [comment]
Can you hover over the parent div to the album cover in element inspector?

**Comment by MrTimscampi** [comment]
I'm having the same results as @ferferga:
image

The swiper-container is properly centered:
image

But swiper-wrapper isn't:
image

The div around the `albumCover` div (could we change this to user kebab-case like everything else, please?) also has the wrong size, which may be the cause for the erroneous calculation leading to off-center slides:
image

**Comment by ferferga** [comment]
@MrTimscampi Sometimes I forgot about the kebab-case, could do a PR later for fixing that 😅.

Here you have my screenshots (going from top to bottom):

image

image

image

image

image

**With a narrower screen:**

image

As @MrTimscampi mentions, the swiper-slide wrapper isn't also properly centered, **so it's not an issue related to the child overflowing the parent**:

image

Trust me when I said that I tried everything to fix this, this has a solution of course but, unless it's a trivial one we're missing, it's not a one-line change for sure 😅.

**Comment by MrTimscampi** [comment]
From testing a bit, the issue seems to be that BlurhashImage has absolute positioning on everything, so it's parent has the wrong size and Swiper can't compute the proper side of one slide, leading to alignment issues.

Fixing the sizes manually in DOM seems to solve the issue for me.

**Comment by ferferga** [comment]
@MrTimscampi I added BlurhashImage at the latest commits in #520, originally it used v-img and the problem was still present.

I did some other layout changes along the way though, so maybe those + the no use of BlurhashImage fixes that, I don't know.

**Comment by Camc314** [comment]
For me, the swiper slide is centered:

Updated
image

Previous:
image

All my addition has done is moved the albumCover to the center of the swiper slide.

**Comment by Camc314** [comment]
On Firefox 84.0.2:

image

The slide is still centered 🤷‍♂️

**Comment by ferferga** [comment]
@MrTimscampi @Camc314 Can you try with my latest changes? I think we might have this finally 100% fixed.

There's an ugly hack though, but I can remove it in my second pass.

**Comment by Camc314** [comment]
This is such a hack lol. But it works :).

👍

**Comment by MrTimscampi** [comment]
Works perfectly here too.

Though, can we remove the padding on the slider?
image

It's really ugly to have covers cut off there (look at the left. Happens on the right too)

**Review by MrTimscampi — APPROVED** [review]

**Review by ferferga — APPROVED** [review]

**Comment by Darkwolf1515** [comment]
Wow. that looks amazing! You've all done such great work on this new client, this is absolutely now the new standard for how media apps should look!

Sadly, can't figure out how to  engage the fullscreen view, i'm on the latest unstable, but cant find the button for it, where is it?

**Pull request merged**
