### PR TITLE
fix(en-us.json): fix two english typos

### PR DESCRIPTION
**Pull request by ThibaultNocchi**

### CODE REVIEW

**Review by ferferga — CHANGES_REQUESTED** [review]
I approved way too fast

@ThibaultNocchi You sure the context here is plural?

If that's the case, we should also change the keys.

**Comment by ThibaultNocchi** [comment]
@ferferga  haha np. You can see other similar sentences are plural. On internet though, answers say both are valid, but it depends on the context (see [here](https://forum.wordreference.com/threads/no-plural-or-singular-noun.1071000/) or [here](https://englishlessonsbrighton.co.uk/followed-singular-plural-noun/)). So I'd say it's pretty safe

**Comment by Camc314** [comment]
I'd say subtitles sounds better, it's probably a good idea to change the keys as well though

**Comment by ThibaultNocchi** [comment]
Ok I'll do this later, I need to make it compatible with #521 as I added similar strings with similar typos.

**Comment by ThibaultNocchi** [comment]
Gonna do it in #521 with the other strings

**Pull request closed without merging**
