### PR TITLE
feat(images): Create custom component for user image

### PR DESCRIPTION
**Pull request by ferferga**
Cherry-picked from #275

### CODE REVIEW

**Review by MrTimscampi — CHANGES_REQUESTED** [review]
This breaks the user icon in the sidebar:

image

Setting an image also completely breaks the client.

**Comment by ferferga** [comment]
@MrTimscampi I tested this before making this PR, even after the cherrypick. However, you're right and for some reason I switched back to the branch and it didn't work.

I merged master and now it works for me, try now please :)

**Comment by MrTimscampi** [comment]
Now it doesn't crash :)

Looks good for the public users, but the main user button inside the app is still really different from what's currently in the client:
image

versus 

image

**Review by MrTimscampi — APPROVED** [review]
The space-evenly bit centers everything and looks weird, but we'll fix it in another PR.

**Pull request merged**
