### PR TITLE
chore: enable strict null checks for typescript

### PR DESCRIPTION
**Pull request by ferferga**

### CODE REVIEW

**Review by Camc314 — APPROVED** [review]

**Comment by MrTimscampi** [comment]
According to the docs, this shouldn't be necessary, as `strict` already enabled it (along with all the other strict mode options).

See: https://www.typescriptlang.org/tsconfig#strict

What's the rationale for adding an explicit one?

**Comment by ThibaultNocchi** [comment]
This was after my comment https://github.com/jellyfin/jellyfin-vue/pull/504#pullrequestreview-561890457 but as @Camc314 pointed out https://github.com/jellyfin/jellyfin-vue/pull/504#issuecomment-754755388, it's because `$auth.user` is of type any.

**Comment by MrTimscampi** [comment]
Closing this, then, as it essentially does nothing and the proper fix would be fixing the typing of $auth.user :)

**Comment by ferferga** [comment]
@MrTimscampi not only for that, but for future developments.

I didn't know that strict enabled it, so thank you for pointing that out!

**Pull request closed without merging**
