### PR TITLE
feat: add scale transition to fullscreen covers

### PR DESCRIPTION
**Pull request by ferferga**
Adds an scale transition to the fullscreen music player:

https://user-images.githubusercontent.com/10274099/107555939-11c28200-6bd8-11eb-96c0-0236cc5dc2e2.mp4

### CODE REVIEW

**Comment by Camc314** [comment]
Looks nice, is it possible to get the nav bar and the progress bar to fade in and out?

**Comment by ferferga** [comment]
@Camc314 You mean the audio controls or the top app bar?

**Comment by Camc314** [comment]
Audio controls on the bottom, and nav bar on the left

**Comment by ferferga** [comment]
Nav bar fading kills performance. I tried switching to v-model as was suggested first but it plays the hiding transition and it's plain bad for performance as there are too many animations happening at once. That's why killing it directly it's better.

As for the audio controls, I plan to get rid of them/refactor for the desktop design once the responsive pass it's done, so It would say we leave this for later, as there's no currently good way of handle the entering transition (leave transition already has fade)

**Comment by ferferga** [comment]
Cherrypicked minor refactor from #633

**Review by ThibaultNocchi — APPROVED** [review]

**Pull request merged**
