### PR TITLE
fix(itemsplugin): fetch all fields of an item when calling getItems

### LINKED ISSUE #1059: "item detail" page get incomplete data
**Describe The Bug**

 "item detail" page get incomplete data when redirect from "person" page.

**Steps To Reproduce**

1. Go to 'item' page
2. Click on any 'person'
3. Click any 'item' from this person
4. 'item' page get incomplete data

**Expected Behavior**

should get full item data

**Screenshots**

image

image

image

**System (please complete the following information):**

- Platform: Windows 10
- Browser: Chrome 78
- Jellyfin Version: 10.7.2

### PR DESCRIPTION
**Pull request by akkisagiraju**
When fetching an array of items for a person/genre/artist, get all the fields of items.

fix #1059

### CODE REVIEW

**Review by ferferga — COMMENTED** [review]
Can you also add this to the userLibrary one?

**Comment by akkisagiraju** [comment]
@ferferga Done.

**Review by ferferga — APPROVED** [review]
LGTM

**Review by MrTimscampi — APPROVED** [review]

**Comment by ThibaultNocchi** [comment]
@jellyfin-bot rebase

**Pull request merged**
