### PR TITLE
feature/139: feat(loginform)

### PR DESCRIPTION
**Pull request by phyzical**
added the ability to support config properties 

* Added ts file to wrap the config file with getters 
* Added config file to support basic defaults 
* implemented default server url based on config properties
 #139

### CODE REVIEW

**Comment by phyzical** [comment]
not sure why npx cz added all that garbage to my commit message (first time using it) ill just do it manually next time haha..

let me know if this wasn't the correct approach :)

**Comment by MrTimscampi** [comment]
I generally like the approach taken by this, but as it is currently, the config file will get bundled by Webpack, which isn't the intent.

The idea is to have one simple file that users can edit at runtime, without rebuilding the entire client.  
It allows easy configuration of things by the admin (For example client name, logo, server address, etc).

Ideally, it should be a `json` file, which would then be copied as-is by webpack to the build directory.

As for the server utils file, it should probably be a Vuex store, since it's available everywhere. At worst, a Nuxt plugin, so that it's available in the context, but a file you have to import manually doesn't seem ideal for this.

**Comment by phyzical** [comment]
@MrTimscampi no worries ill have another crack :)

**Comment by bbogdanov** [comment]
What do you think about adding something similar to this idea

```
const serverLocation = window.location.host;

fetch(`http://${serverLocation}:8096/`, { method: 'OPTIONS' }).then(data => { 
 // server exist => check if it is really a Jellyfin server => update the store
}).catch(err => {
 // 1. check localStorage/cookie for already stored server location => use stored one

 // 2. server doesn't exist, let the user provide the server location => update the store => store the location in localStorage/cookie
});
```

I can help with that if help needed.

**Comment by phyzical** [comment]
hey sorry ive been busy, havnt had a chance to update this, eill try to get to it this week

@bbogdanov happy to use this approach instead, but i guess it would come down to what else this config may hold in the future?

@MrTimscampi what do you think?

**Comment by MrTimscampi** [comment]
So, the idea is to mainly reproduce what this file does on the current web client (specifically the "servers" and "multiServer" keys): https://github.com/jellyfin/jellyfin-web/blob/master/src/config.json

@bbogdanov's solution is part of it, but there's also more to it.

Basically:

* If `multiServer` is set, the client shows everything related to server selection (`Select server` buttons, redirection to the server selection page if none is set, etc)
  * If the `servers` key is set, pre-fill the list of available servers (make sure to check they're really Jellyfin servers first, of course)
* If `multiServer` is not set, the client hides everything related to server selections and uses a few things to determine what server to use:
  * If the `servers` key is populated, use that
  * If it's not, try a few common candidates
  * If none of the candidates work, act as if `multiServer` is set to `true`

The catch here is that all of this stuff has to be configurable by an admin with access to the files. So it shouldn't be part of the bundle that Webpack produces.

Basic structure after build should look roughly like this:
```
jellyfin-vue
|-- index.html
|-- bundle.js (produced by webpack, minified and all that)
|-- config.json (basically just copied straight over, not minified and easy to edit)
```

I hope this makes more sense with this explanation. It's basically a way to allow for configuring things in the client without having to build it, since we want users to be able to run a standalone web client separately from the server.

**Comment by bbogdanov** [comment]
> So, the idea is to mainly reproduce what this file does on the current web client (specifically the "servers" and "multiServer" keys): https://github.com/jellyfin/jellyfin-web/blob/master/src/config.json
> 
> @bbogdanov's solution is part of it, but there's also more to it.
> 
> Basically:
> 
> * If `multiServer` is set, the client shows everything related to server selection (`Select server` buttons, redirection to the server selection page if none is set, etc)
>   
>   * If the `servers` key is set, pre-fill the list of available servers (make sure to check they're really Jellyfin servers first, of course)
> * If `multiServer` is not set, the client hides everything related to server selections and uses a few things to determine what server to use:
>   
>   * If the `servers` key is populated, use that
>   * If it's not, try a few common candidates
>   * If none of the candidates work, act as if `multiServer` is set to `true`
> 
> The catch here is that all of this stuff has to be configurable by an admin with access to the files. So it shouldn't be part of the bundle that Webpack produces.
> 
> Basic structure after build should look roughly like this:
> 
> ```
> jellyfin-vue
> |-- index.html
> |-- bundle.js (produced by webpack, minified and all that)
> |-- config.json (basically just copied straight over, not minified and easy to edit)
> ```
> 
> I hope this makes more sense with this explanation. It's basically a way to allow for configuring things in the client without having to build it, since we want users to be able to run a standalone web client separately from the server.

Don't you think this can be done by having a dialog in the login page where you can edit these at runtime? We can set the default configuration inside the `Store` and then save settings changes inside localStorage and extract the client provided settings on initial app load.

Something like 
``` 
// Mutations
async saveSettings(state, settings) {
   state = settings;
}

// Getters
getSavedSettings(state) {
  if (!localStoage) return;

  const settings = localStorage.get('clientSettings');
  
  if (!settings) {
    return;
  }

  return settings;
}

getClientSettings(state) {
  const savedSettings = $store.getter.clientSettings.getSavedSettings(); 
 
  return savedSettings || state;
}

// Actions
async saveSettings({ dispatch, commit }, settings) {
   if (!settings) return;

  await dispatch('saveSettingsInStorage`, settings);

  commit('saveSettings', settings);
}

saveSettingsInStorage(_, settings) {
   localStorage.set('clientSettings', settings); // We will need to make sure on initial app load that localStorage exist
}

```
> I hope this makes more sense with this explanation. It's basically a way to allow for configuring things in the client without having to build it, since we want users to be able to run a standalone web client separately from the server.

Maybe I am missing something. Could you please provide a situation when I as a user would want to change a config file manually inside my client `dist` folder?

**Comment by MrTimscampi** [comment]
> Don't you think this can be done by having a dialog in the login page where you can edit these at runtime? We can set the default configuration inside the `Store` and then save settings changes inside localStorage and extract the client provided settings on initial app load.

But doing that, these settings will only be saved for the client who made these changes. The idea here is to have all the clients that connect to that web client instance to share these settings.

> Maybe I am missing something. Could you please provide a situation when I as a user would want to change a config file manually inside my client dist folder?

As a server admin, you have two server running, plus a separate web client you host. You want the one web client to act as a front for both servers. This allows you to configure the web client to do just that.

Note that, at some point, these won't be the only settings living in there. I'm sure @jellyfin/core can provide more info if needed.

**Comment by bbogdanov** [comment]
> > Don't you think this can be done by having a dialog in the login page where you can edit these at runtime? We can set the default configuration inside the `Store` and then save settings changes inside localStorage and extract the client provided settings on initial app load.
> 
> But doing that, these settings will only be saved for the client who made these changes. The idea here is to have all the clients that connect to that web client instance to share these settings.
> 
> > Maybe I am missing something. Could you please provide a situation when I as a user would want to change a config file manually inside my client dist folder?
> 
> As a server admin, you have two server running, plus a separate web client you host. You want the one web client to act as a front for both servers. This allows you to configure the web client to do just that.
> 
> Note that, at some point, these won't be the only settings living in there. I'm sure @jellyfin/core can provide more info if needed.

Got it. Thank you!

**Comment by Camc314** [comment]
Instead (or as well as) a config.json, it would also be nice to specify if it should be single/multi server through environmental variables.

**Comment by MrTimscampi** [comment]
I'm converting this to a draft in order to help me figure out what's in review and what needs reworking, since I'm starting to get a bit lost with all the activity on the repository :wink:

**Comment by bbogdanov** [comment]
@ferferga I advise you to take a look at the comments cause the PR at the current stage is like 25% of what has to be done by this task.

**Comment by MrTimscampi** [comment]
This has some overlap with #343 and, similarly, it shouldn't connect to anything by default.

It should also inject the config as a proper Nuxt plugin, not as exports/imports (So we could access config options with something like `this.$config.multiServer` or something).

I would also see it more as this kind of structure, to be able to define multiple default servers:
```json
{
  "servers": [
      {
        "ssl": false,
        "url": "127.0.0.1",
        "port": 8096,
        "baseUrl": ""
      }
  ],
  "multiServer": true
}
```

**Comment by ThibaultNocchi** [comment]
What's the state of this? Also, can't the list of servers be shortened to a list of strings, as all the parameters just define an URL

**Comment by MrTimscampi** [comment]
This looks pretty much abandoned, so I'm closing it. It needs to be redone entirely anyway, so feel free to reopen if you want to redo it.

**Pull request closed without merging**
