### PR TITLE
feat(audio controls): improve responsiveness of audio controls

### PR DESCRIPTION
**Pull request by Camc314**
**Changes**

 - Hides: Shuffle, repeat and itemmenu on xs devices
 - Hides Volume control on lg and smaller devices
 - Decreases cover art size on smaller devices

**Narrowest**
image

**Wider**
image

**Even wider**
image

**Wider still...**

image

### CODE REVIEW

**Comment by ferferga** [comment]
Maybe not for this PR but what about moving shuffle, repeat, stop and such (not volume slider of course) to the item menu? I think that would be the best solution.

**Comment by Camc314** [comment]
I think skipping, and play/pausing are commands that are most likely to be used, this is pretty similar to spotify, the youtube mini player, and plex amp. If we were to move them to the item menu, it is still the same number of clicks as going to the full screen player. I'm open to other opinion, but I think that adding the item menu as well makes it a tad too cluttered.

If anyone has any other thoughts, I'd be interested to hear them

**Comment by ferferga** [comment]
@Camc314 Maybe I haven't explained myself

**Wider still**: As is right now
**Even wider**: As is right now
**Wider**: As is, but add menu item with the "Stop playback" option.
**Narrower**: As is, but add menu item with previous, repeat, shuffle and stop playback.

Maybe the options in narrower are the ones more up for discussion, but imo the stop playback should always be present.

I forgot in my PR and it would be nice if it's here instead of the one where I plan to expand more music features: click anywhere in the footer in the layout where there's no full screen button to open full screen music page.

**Comment by MrTimscampi** [comment]
> **Narrower**: As is, but add menu item with previous, repeat, shuffle and stop playback.

I agree with @Camc314 for this, an item menu is kind of useless since one tap on the footer should bring you to the full screen and then those controls are available.

I would even hide the repeat and shuffle on the wider one, honestly, but that's up for discussion.

**Comment by ThibaultNocchi** [comment]
I quite like the decisions @Camc314 made on these screenshots. I think you could even add the stop playback button even on the narrower screens. And yeah clicking on the footer should put the player to full screen

**Review by MrTimscampi — APPROVED** [review]

**Pull request merged**
