### PR TITLE
feat: permanent scrollbars in default layout only

### PR DESCRIPTION
**Pull request by ferferga**
The splashcreen and video/music/login pages with scrollbars were really ugly

### CODE REVIEW

**Review by ThibaultNocchi — COMMENTED** [review]
Maybe we should add the same class logic to the server layout?

**Comment by ferferga** [comment]
@ThibaultNocchi I had the same doubt.

I don't expect that page to be scrollable too often (maybe if an user has tons and tons of servers?) and scroll itself will still be possible (so a minor jump is not as noticeable?)

The problem is when the page is constantly jumping because of the scrollbar

**Comment by ThibaultNocchi** [comment]
Ok just a personal thing. I'd reverse the logic: don't apply the class by default and only apply it on the FS pages. To me it's more logic as those are the "edge" cases, not the default. But that's a preference.

**Comment by ferferga** [comment]
@ThibaultNocchi Thought the same when doing this, so our thinking process is very similar :)

However, doing that requires more lines of code (to cover server and fullpage layout) plus I can also give the upside down to your statement: What you say is to keep Vuetify's defaults as our first defaults, while what I want to is to stick with browser's defaults first (removing the class that overrides Vuetify's default when accessing our default layout, and doing the reverse thing when going out)

**Review by ThibaultNocchi — APPROVED** [review]
LGTM

**Pull request merged**
