### PR TITLE
German translation

### PR DESCRIPTION
**Pull request by cromefire**
Nothing fancy just a translation

### CODE REVIEW

**Comment by nielsvanvelzen** [comment]
https://translate.jellyfin.org/projects/jellyfin/jellyfin-vue/de/

**Comment by cromefire** [comment]
Is it also added to weblate?

**Comment by cromefire** [comment]
Apparently, but the site is just really confusing

**Comment by cromefire** [comment]
But it still has to be added to the nuxt config, which probably doesn't work automatically

**Comment by nielsvanvelzen** [comment]
@MrTimscampi will do that soon for all new languages

**Pull request closed without merging**
