### PR TITLE
Add missing file to collect coverage from

### PR DESCRIPTION
**Pull request by Camc314**

### CODE REVIEW

**Review by ThibaultNocchi — APPROVED** [review]
Is there a reason for the tabulation for the new line? (Or is it GH Android that's just messing around)

**Comment by Camc314** [comment]
I think it might just be gh android, it looks fine on web

**Comment by Camc314** [comment]
image

**Comment by ThibaultNocchi** [comment]
All good then!

**Review by MrTimscampi — APPROVED** [review]

**Pull request merged**
