### PR TITLE
revert(card): reverts 4a72c51, should fix missing images on home screen

### PR DESCRIPTION
**Pull request by Camc314**
Reverts 4a72c51

### CODE REVIEW

**Comment by MrTimscampi** [comment]
As said in the original PR, this isn't a bug. It's simply waiting for #520 in order to have fallback from thumbs to backdrops.

The behavior in 4a72c51 is the same as jf-web, we're just missing the fallback, which is dependent on the PR mentioned above.

**Comment by ferferga** [comment]
@Camc314 @MrTimscampi Does this need rebasing now that #520 is in?

**Comment by ThibaultNocchi** [comment]
Can we delete it?

**Comment by ferferga** [comment]
Oops hit remove by accident. Should be recoverable for the next 24 hours though. Do we need them? If this was closed, I guess not

**Comment by Camc314** [comment]
It is one of the 150+ branches I've got locally lol

**Pull request closed without merging**
